/**
 * gen-commands-json.ts — 从 sdd-router.ts SUBCOMMANDS + api-runner.ts switch case
 * 提取命令清单，输出 commands.generated.json 供 validator Check #12 比对。
 *
 * 用法: bun run scripts/gen-commands-json.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const ROUTER = resolve(ROOT, "extensions/sdd-extension/sdd-router.ts");
const RUNNER = resolve(ROOT, "src/cli/api-runner.ts");
const OUT = resolve(ROOT, "src/cli/lib/orchestration/commands.generated.json");

function extractSubcommands(routerSrc: string): string[] {
  // 提取 SUBCOMMANDS: Record<string, Handler> = { ... } 块的键
  const blockMatch = routerSrc.match(/SUBCOMMANDS[^=]*=\s*\{([^}]*)\}/s);
  if (!blockMatch) throw new Error("无法定位 SUBCOMMANDS 块");
  const keys = new Set<string>();
  for (const m of blockMatch[1].matchAll(/(?:^|\n)\s+"?([a-zA-Z][a-zA-Z0-9_-]+)"?\s*:/g)) {
    keys.add(m[1]);
  }
  return [...keys].sort();
}

function extractApiRunnerCases(runnerSrc: string): string[] {
  // 提取 switch (cmd) { case "...": ... } 的 case 字符串
  const cases = new Set<string>();
  for (const m of runnerSrc.matchAll(/case\s+"([a-zA-Z][a-zA-Z0-9_-]+)"\s*:/g)) {
    cases.add(m[1]);
  }
  return [...cases].sort();
}

const routerSrc = readFileSync(ROUTER, "utf-8");
const runnerSrc = readFileSync(RUNNER, "utf-8");

const subcommands = extractSubcommands(routerSrc);
const apiRunnerCases = extractApiRunnerCases(runnerSrc);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  JSON.stringify(
    {
      _comment: "AUTO-GENERATED by scripts/gen-commands-json.ts — 勿手改",
      _source: { subcommands: "extensions/sdd-extension/sdd-router.ts", apiRunnerCases: "src/cli/api-runner.ts" },
      subcommands,
      apiRunnerCases,
      // api-runner 允许多出的 case（legacy 兼容 + gate 5 阶段拆分）
      allowedExtraInRunner: ["legacy-status", "gate-lint", "gate-test", "gate-review", "gate-precommit", "gate-commit"],
    },
    null,
    2,
  ) + "\n",
);

console.log(`生成 ${OUT.replace(ROOT, "")}:`);
console.log(`  subcommands (${subcommands.length}): ${subcommands.join(", ")}`);
console.log(`  apiRunnerCases (${apiRunnerCases.length}): ${apiRunnerCases.join(", ")}`);
